### ISSUE TITLE
TypeError: Cannot call method 'abort' of null

### ISSUE THREAD

**Issue by stevefister** [SpiderStrategies/node-tweet-stream#36]
Any ideas?? Thanks!

/mnt/sda1/node-tweet-stream/node_modules/node-tweet-stream/lib/twitter.js:270
  this.stream.abort()
              ^
TypeError: Cannot call method 'abort' of null
    at Twitter.abort (/mnt/sda1/node-tweet-stream/node_modules/node-tweet-stream/lib/twitter.js:270:15)
    at null.<anonymous> (/mnt/sda1/node-tweet-stream/node_modules/node-tweet-stream/lib/twitter.js:257:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/mnt/sda1/node-tweet-stream/node_modules/node-tweet-stream/node_modules/request/request.js:965:12)
    at IncomingMessage.EventEmitter.emit (events.js:95:17)
    at readableAddChunk (_stream_readable.js:132:14)
    at IncomingMessage.Readable.push (_stream_readable.js:113:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:140:22)
    at CleartextStream.socketOnData [as ondata] (http.js:1535:20)
    at CleartextStream.read [as _read] (tls.js:470:10)

**Comment by nathanbowser** [comment]
Looks like a bug. PR welcome.

**Comment by stevefister** [comment]
I tried replacing abort() method with destroy(). That stops the error, but then nothing is received. I'm not much of a help as I'm very new to node 😐

**Comment by jeveloper** [comment]
I believe the steps to recreate this:

1. track a few items, especially if they are coming in at a high rate
2. call tw.untrackAll(); 
3. track another keyword , BOOM this happens.

Using github master for my code, same thing happens

node-tweet-stream/lib/twitter.js:287
  this.stream.abort()

@nathanbowser not entirely sure if there are best practices clearing filters while something is coming in. Any ideas as to why this is happening?
Thank you for good work.

**Comment by nathanbowser** [comment]
Yea, I figured it out. Fix coming shortly.

**Comment by nathanbowser** [comment]
I had trouble getting a test to reproduce this, but I think it's because you're hitting a twitter rate limit, which aborts the stream in the response callback. 

```
+ node-tweet-stream@1.9.1

```

**Comment by jeveloper** [comment]
Hey Nathan, thanks for fixing this :)
I think its a great library. Im having a lot of  trouble with this bug, so ill be sure to test.

**Comment by nathanbowser** [comment]
@jeveloper awesome, please let me know!

**Comment by nathanbowser** [comment]
@jeveloper Did you ever get a chance to try out my fix?

**Comment by jeveloper** [comment]
Yes it does work :)
